version: '3'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: monitor
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    ports:
      - "3002:3002"
    networks:
      - app_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
